title: essays by spoons
#description: things that I've written
theme: minima

titles_from_headings:
  strip_title: true

exclude:
  - README.md
  - "md-tuuner/**"
  - "**/*.base.md"
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
